application: psycolorg
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  mime_type: image/x-icon
  upload: favicon.ico

- url: /.*
  static_files: index.html
  upload: index.html

